"""
NEXUS SPECTER PRO — Attack Narrative Generator
Uses Specter AI to generate a realistic attacker narrative:
"How a threat actor would enter, move laterally, and achieve their objective."
Translates technical findings into a compelling executive story.
by OPTIMIUM NEXUS LLC | contact@optimiumnexus.com
"""

import json, logging
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime
from rich.console import Console
from rich.panel import Panel

console = Console()
log = logging.getLogger("nsp.intelligence.narrative")


NARRATIVE_PROMPT_TEMPLATE = """You are a senior red team operator writing a realistic attack narrative for an executive report.

Based on the following security assessment data, write a compelling, realistic narrative that describes:
1. **Initial Access** — How a threat actor would first gain a foothold
2. **Reconnaissance** — What they would discover about the internal environment
3. **Lateral Movement** — How they would move from the initial foothold toward high-value targets
4. **Privilege Escalation** — How they would gain elevated access
5. **Impact** — What they could ultimately do (data exfiltration, ransomware, sabotage)

Write in third person ("A threat actor..."). Be specific — reference actual findings by name.
Tone: professional, factual, not alarmist but clear about risk.
Length: 500-700 words. No JSON — flowing prose only.

Target: {target}
Client: {client}

Top Findings:
{findings_summary}

Infrastructure Context:
{infra_context}

Attack Paths Identified:
{attack_paths}

Threat Intelligence:
{threat_intel}
"""

FALLBACK_NARRATIVE_TEMPLATE = """
## Attack Scenario: {target}

### Initial Access

A threat actor targeting **{target}** would most likely begin by exploiting one of the {critical_count} critical or {high_count} high-severity vulnerabilities identified during this assessment. The most accessible entry point is the externally exposed web application infrastructure, which presents {total_findings} vulnerabilities across the assessed attack surface.

{initial_access_detail}

### Internal Reconnaissance

Once inside, the attacker would leverage discovery techniques to map the internal environment. With {open_ports} open ports identified across the infrastructure, the attacker would quickly enumerate active services, identify domain controllers, and map trust relationships between systems.

{recon_detail}

### Lateral Movement & Privilege Escalation

From the initial foothold, lateral movement would be facilitated by {lateral_detail}. The presence of credential-related weaknesses means that privilege escalation to domain administrator level cannot be ruled out within a realistic timeframe.

### Potential Impact

At full compromise, a threat actor would have the capability to:
- Access and exfiltrate sensitive data across the assessed systems
- Deploy ransomware or destructive malware across the network
- Maintain persistent access via backdoors or legitimate administrative tools
- Disrupt business operations by targeting critical infrastructure components

### Assessment Summary

This assessment identified a **{risk_level}** overall risk posture. Immediate remediation of the critical and high-severity findings is strongly recommended to significantly reduce the probability and impact of a successful attack.

*Narrative generated by NEXUS SPECTER PRO — OPTIMIUM NEXUS LLC*
"""


@dataclass
class NarrativeResult:
    target:      str
    client:      str
    narrative:   str
    source:      str    # ai | template
    word_count:  int    = 0
    sections:    list   = field(default_factory=list)
    generated_at:str    = field(default_factory=lambda: datetime.utcnow().isoformat())


class AttackNarrative:
    """
    Attack Narrative Generator for NEXUS SPECTER PRO.
    Combines all mission data into a coherent attacker story.
    Primary: Specter AI (Claude API) for high-quality narrative.
    Fallback: Template-based narrative when AI unavailable.
    """

    def __init__(self, ai_engine=None, output_dir: str = "/tmp/nsp_reports"):
        self.ai          = ai_engine
        self.output_dir  = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _summarise_findings(self, findings: dict) -> str:
        lines = []
        for sev in ["critical","high","medium"]:
            for f in findings.get("by_severity",{}).get(sev,[])[:5]:
                lines.append(f"- [{sev.upper()}] {f.get('name','')} | {f.get('host','')}")
        return "\n".join(lines) or "No critical/high findings."

    def _infra_context(self, session: dict) -> str:
        recon    = session.get("recon",{})
        ports    = recon.get("ports",{})
        subs     = recon.get("subdomains",{})
        lines    = []
        n_ports  = len(ports.get("masscan_ports",[]))
        n_subs   = len(subs.get("all_subdomains",[]))
        if n_ports:  lines.append(f"- {n_ports} open ports discovered")
        if n_subs:   lines.append(f"- {n_subs} subdomains enumerated")
        cloud = recon.get("cloud",{})
        if cloud.get("public_assets",0):
            lines.append(f"- {cloud['public_assets']} public cloud assets exposed")
        return "\n".join(lines) or "Standard enterprise infrastructure."

    def _attack_paths_summary(self, attack_graph: dict) -> str:
        paths = attack_graph.get("attack_paths",[])
        if not paths:
            return "Attack path data not available."
        lines = []
        for p in paths[:3]:
            nodes = p.get("nodes",[])
            feas  = p.get("feasibility","")
            lines.append(f"- Path ({feas}): {' → '.join(str(n) for n in nodes)}")
        return "\n".join(lines)

    def _threat_intel_summary(self, intel: dict) -> str:
        if not intel:
            return "No threat intelligence data."
        score = intel.get("threat_score",0)
        level = intel.get("threat_level","")
        vulns = intel.get("known_vulns",[])
        lines = [f"- Threat Score: {score}/100 ({level})"]
        if vulns:
            lines.append(f"- Known CVEs on infrastructure: {', '.join(vulns[:5])}")
        return "\n".join(lines)

    def _generate_ai_narrative(self, target: str, client: str,
                                session: dict) -> str:
        if not self.ai:
            return ""
        findings    = session.get("vuln_scan",{})
        prompt = NARRATIVE_PROMPT_TEMPLATE.format(
            target        = target,
            client        = client,
            findings_summary = self._summarise_findings(findings),
            infra_context    = self._infra_context(session),
            attack_paths     = self._attack_paths_summary(
                                 session.get("attack_graph",{})),
            threat_intel     = self._threat_intel_summary(
                                 session.get("threat_intel",{})),
        )
        try:
            console.print("[#00FFD4]  [NARRATIVE] Generating AI narrative...[/#00FFD4]")
            return self.ai._query(prompt, max_tokens=2048)
        except Exception as e:
            log.warning(f"[NARRATIVE] AI failed: {e}")
            return ""

    def _generate_template_narrative(self, target: str, client: str,
                                      session: dict) -> str:
        findings  = session.get("vuln_scan",{})
        by_sev    = findings.get("by_severity",{})
        crit_c    = len(by_sev.get("critical",[]))
        high_c    = len(by_sev.get("high",[]))
        total     = sum(len(v) for v in by_sev.values())
        recon     = session.get("recon",{})
        n_ports   = len(recon.get("ports",{}).get("masscan_ports",[]))
        risk_level= "CRITICAL" if crit_c > 0 else "HIGH" if high_c > 0 else "MEDIUM"

        # Initial access detail
        if crit_c > 0:
            first_crit = by_sev["critical"][0].get("name","") if by_sev.get("critical") else ""
            ia_detail  = (f"Specifically, the **{first_crit}** vulnerability "
                          f"provides a direct, unauthenticated path to remote code "
                          f"execution, requiring minimal skill to exploit using "
                          f"publicly available tools.")
        else:
            ia_detail = ("The external attack surface presents multiple medium and "
                          "high-severity vulnerabilities that, in combination, "
                          "could enable initial access through credential attacks "
                          "or application-layer exploitation.")

        # Recon detail
        if n_ports > 20:
            recon_detail = (f"With {n_ports} open ports, the attacker would enumerate "
                            f"running services and identify misconfigurations within hours.")
        else:
            recon_detail = "The attacker would use passive reconnaissance to map the environment."

        # Lateral detail
        bh   = session.get("post_exploit",{}).get("bloodhound",{})
        kerb = bh.get("kerberoastable",[])
        if kerb:
            lateral_detail = (f"Kerberoasting against {len(kerb)} service account(s) "
                              f"({', '.join(kerb[:2])}) to obtain crackable ticket hashes")
        else:
            lateral_detail = "discovered credentials and pass-the-hash techniques"

        return FALLBACK_NARRATIVE_TEMPLATE.format(
            target             = target,
            critical_count     = crit_c,
            high_count         = high_c,
            total_findings     = total,
            open_ports         = n_ports,
            risk_level         = risk_level,
            initial_access_detail = ia_detail,
            recon_detail       = recon_detail,
            lateral_detail     = lateral_detail,
        )

    def export_html(self, result: NarrativeResult) -> Path:
        # Convert markdown-style bold to HTML
        narrative_html = result.narrative
        narrative_html = narrative_html.replace("**", "<strong>", 1)
        import re
        narrative_html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", narrative_html)
        narrative_html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", narrative_html, flags=re.MULTILINE)
        narrative_html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", narrative_html, flags=re.MULTILINE)
        narrative_html = re.sub(r"^- (.+)$", r"<li>\1</li>", narrative_html, flags=re.MULTILINE)
        narrative_html = narrative_html.replace("\n\n", "</p><p>")

        html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>NSP Attack Narrative — {result.target}</title>
<style>
  body{{background:#0A0A0A;color:#E8E8E8;font-family:'Segoe UI',sans-serif;margin:0;}}
  .header{{background:#0D0D0D;border-bottom:2px solid #7B00FF;padding:14px 32px;
    display:flex;justify-content:space-between;align-items:center;}}
  h1{{color:#7B00FF;font-size:16px;letter-spacing:4px;margin:0;}}
  .page{{padding:40px;max-width:900px;margin:0 auto;line-height:1.9;}}
  h2{{color:#7B00FF;font-size:18px;margin:32px 0 12px;border-left:4px solid #7B00FF;
    padding-left:16px;}}
  h3{{color:#00FFD4;font-size:14px;margin:24px 0 8px;}}
  p{{color:#C8C8C8;margin:10px 0;}}
  li{{color:#C8C8C8;margin:6px 0;}}
  strong{{color:#E8E8E8;}}
  .meta{{background:#0D0D0D;border:1px solid #1E1E1E;border-radius:8px;
    padding:16px 20px;margin-bottom:32px;font-size:12px;}}
  .meta span{{color:#00FFD4;}}
  .footer{{border-top:1px solid #1E1E1E;padding:16px 40px;color:#333;font-size:10px;
    display:flex;justify-content:space-between;margin-top:40px;}}
</style>
</head><body>
<div class="header">
  <h1>⚡ NSP — ATTACK NARRATIVE</h1>
  <div style="color:#555;font-size:11px;">CONFIDENTIAL | OPTIMIUM NEXUS LLC</div>
</div>
<div class="page">
  <div class="meta">
    <span>Target:</span> {result.target} &nbsp;|&nbsp;
    <span>Client:</span> {result.client} &nbsp;|&nbsp;
    <span>Generated:</span> {result.generated_at[:10]} &nbsp;|&nbsp;
    <span>Source:</span> {result.source.upper()} &nbsp;|&nbsp;
    <span>Words:</span> {result.word_count}
  </div>
  <h2>Threat Actor Attack Scenario</h2>
  <p>{narrative_html}</p>
</div>
<div class="footer">
  <span>NEXUS SPECTER PRO — by OPTIMIUM NEXUS LLC</span>
  <span>contact@optimiumnexus.com</span>
</div>
</body></html>"""

        out = self.output_dir / f"{result.target.replace('.','_')}_narrative.html"
        out.write_text(html, encoding="utf-8")
        return out

    def run(self, target: str, client: str = "Client",
             session: dict = None) -> dict:
        console.print(f"[bold #7B00FF]  📖 Attack Narrative — {target}[/bold #7B00FF]")
        session = session or {}

        # Try AI first, fallback to template
        narrative = self._generate_ai_narrative(target, client, session)
        source    = "ai"
        if not narrative:
            console.print("[dim]  → AI unavailable — using template narrative[/dim]")
            narrative = self._generate_template_narrative(target, client, session)
            source    = "template"

        word_count = len(narrative.split())
        result = NarrativeResult(
            target     = target,
            client     = client,
            narrative  = narrative,
            source     = source,
            word_count = word_count,
        )

        # Print preview
        preview = " ".join(narrative.split()[:60])
        console.print(Panel(
            f"[italic]{preview}...[/italic]",
            title=f"[bold #7B00FF]📖 NARRATIVE PREVIEW[/bold #7B00FF]",
            border_style="#7B00FF",
        ))

        html_path = self.export_html(result)
        console.print(f"[bold #00FFD4]  ✅ Narrative: {html_path} "
                       f"({word_count} words, source: {source})[/bold #00FFD4]")

        return {
            "target":     target,
            "narrative":  narrative,
            "source":     source,
            "word_count": word_count,
            "html":       str(html_path),
        }
